name: Robot Framework Tests Frontend

on:
  pull_request:
    branches:
      - main

jobs:
  robot-framework-testes-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-seleniumlibrary
          pip install robotframework-requests
          pip install robotframework-faker
          pip install webdriver-manager
      - name: Setup Chrome and ChromeDriver
        run: |
          # Usar o Chrome já instalado no Ubuntu
          google-chrome --version
          # Instalar ChromeDriver compatível
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
          wget -q https://storage.googleapis.com/chrome-for-testing-public/$(curl -s https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_${CHROME_VERSION})/linux64/chromedriver-linux64.zip
          unzip -q chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version
      - name: Run Robot Framework Tests
        env:
          CI: true
        run: |
          cd robot-framework-testes-frontend
          robot --outputdir results tests/login/
        continue-on-error: false

      - name: Check Test Results
        run: |
          cd robot-framework-testes-frontend/results
          if grep -q "FAIL" output.xml; then
            echo "❌ Testes falharam!"
            exit 1
          else
            echo "✅ Todos os testes passaram!"
          fi
